security:
  auth-mode: keycloak
  oauth2:
    client-id: spring-app

spring:
  config:
    import: classpath:application-local.properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://app.local/auth/realms/ninjasmoke

      client:
        provider:
          keycloak:
            authorization-uri: http://app.local/auth/realms/ninjasmoke/protocol/openid-connect/auth
            token-uri: http://app.local/auth/realms/ninjasmoke/protocol/openid-connect/token
            jwk-set-uri: http://app.local/auth/realms/ninjasmoke/protocol/openid-connect/certs
            user-info-uri: http://app.local/auth/realms/ninjasmoke/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

        registration:
          keycloak:
            client-id: spring-app
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"